"""Generate committed OpenAPI, JSON Schemas, and TypeScript types from Python contracts."""

from __future__ import annotations

import json
import tempfile
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter

from stata_research_agent.interfaces.api.app import WorkspaceHost, create_app
from stata_research_agent.runtime.ipc_contract import AgentIpcMessage, WorkerIpcInput
from stata_research_agent.runtime.tool_contract import (
    CanonicalToolCallEnvelope,
    CanonicalToolResultEnvelope,
    CompletionManifestEnvelope,
    OperationAttemptEnvelope,
    OperationEnvelope,
)

ROOT = Path(__file__).parents[1]


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def schema_to_ts(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(item) for item in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(schema_to_ts(item) for item in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(schema_to_ts(item) for item in schema["oneOf"])
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(schema_to_ts({**schema, "type": item}) for item in schema_type)
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        return f"ReadonlyArray<{schema_to_ts(schema.get('items', {}))}>"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        additional = schema.get("additionalProperties")
        if not properties and additional is not None:
            if additional is False:
                return "Readonly<Record<string, never>>"
            value_type = "unknown" if additional is True else schema_to_ts(additional)
            return f"Readonly<Record<string, {value_type}>>"
        required = set(schema.get("required", []))
        fields = []
        for name, field_schema in sorted(properties.items()):
            optional = "" if name in required else "?"
            fields.append(f"  readonly {json.dumps(name)}{optional}: {schema_to_ts(field_schema)};")
        if not fields:
            return "Readonly<Record<string, never>>"
        return "{\n" + "\n".join(fields) + "\n}"
    return "unknown"


def generate_typescript(openapi: dict[str, Any]) -> str:
    lines = ["// Generated by tools/generate_contracts.py. Do not edit.", ""]
    schemas = openapi["components"]["schemas"]
    for name, schema in sorted(schemas.items()):
        lines.append(f"export type {name} = {schema_to_ts(schema)};")
        lines.append("")
    lines.extend(
        [
            "let browserSessionToken: string | undefined;",
            "",
            "export function setBrowserSessionToken(token: string): void {",
            "  browserSessionToken = token;",
            "}",
            "",
            "export function clearBrowserSessionToken(): void {",
            "  browserSessionToken = undefined;",
            "}",
            "",
            "export async function apiFetch(",
            "  input: string, init: RequestInit = {},",
            "): Promise<Response> {",
            "  const headers = new Headers(init.headers);",
            "  if (browserSessionToken !== undefined) {",
            "    headers.set('x-stata-browser-session', browserSessionToken);",
            "  }",
            "  return globalThis.fetch(input, { ...init, headers });",
            "}",
            "",
            "export type ApiEventStreamEvent = {",
            "  readonly event: string;",
            "  readonly id?: string;",
            "  readonly data: string;",
            "};",
            "",
            "export async function consumeApiEventStream(",
            "  url: string,",
            "  handlers: {",
            "    readonly onOpen: () => void;",
            "    readonly onEvent: (event: ApiEventStreamEvent) => void;",
            "  },",
            "  signal: AbortSignal,",
            "): Promise<void> {",
            "  const response = await apiFetch(url, {",
            "    headers: { accept: 'text/event-stream' },",
            "    signal,",
            "  });",
            "  if (!response.ok || response.body === null) {",
            "    throw new Error(`Event stream rejected with status ${response.status}`);",
            "  }",
            "  handlers.onOpen();",
            "  const reader = response.body.getReader();",
            "  const decoder = new TextDecoder();",
            "  let pending = '';",
            "  const dispatchBlock = (block: string): void => {",
            "    let event = 'message';",
            "    let id: string | undefined;",
            "    const data: string[] = [];",
            "    for (const rawLine of block.split('\\n')) {",
            "      const line = rawLine.endsWith('\\r') ? rawLine.slice(0, -1) : rawLine;",
            "      if (line.startsWith(':') || line.length === 0) continue;",
            "      const separator = line.indexOf(':');",
            "      const field = separator < 0 ? line : line.slice(0, separator);",
            "      let value = separator < 0 ? '' : line.slice(separator + 1);",
            "      if (value.startsWith(' ')) value = value.slice(1);",
            "      if (field === 'event') event = value;",
            "      else if (field === 'id') id = value;",
            "      else if (field === 'data') data.push(value);",
            "    }",
            "    if (data.length === 0) return;",
            (
                "    handlers.onEvent({ event, ...(id === undefined ? {} : { id }), "
                "data: data.join('\\n') });"
            ),
            "  };",
            "  while (true) {",
            "    const chunk = await reader.read();",
            "    pending += decoder.decode(chunk.value, { stream: !chunk.done });",
            "    pending = pending.replaceAll('\\r\\n', '\\n');",
            "    let boundary = pending.indexOf('\\n\\n');",
            "    while (boundary >= 0) {",
            "      dispatchBlock(pending.slice(0, boundary));",
            "      pending = pending.slice(boundary + 2);",
            "      boundary = pending.indexOf('\\n\\n');",
            "    }",
            "    if (chunk.done) break;",
            "  }",
            "  if (pending.trim().length > 0) dispatchBlock(pending);",
            "}",
            "",
        ]
    )
    paths = sorted(openapi["paths"])
    lines.append("export const API_V1_PATHS = [")
    lines.extend(f"  {json.dumps(path)}," for path in paths)
    lines.append("] as const;")
    lines.append("")
    if "/api/v1/meta" in openapi["paths"]:
        lines.extend(
            [
                "export async function getMeta(",
                "  baseUrl: string, signal?: AbortSignal,",
                "): Promise<MetaResponse> {",
                "  const response = await globalThis.fetch(",
                "    `${baseUrl}/api/v1/meta`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                (
                    "  if (!response.ok) throw new Error("
                    "`Meta request failed with ${response.status}`);"
                ),
                "  return await response.json() as MetaResponse;",
                "}",
                "",
            ]
        )
    if "/api/v1/session/exchange" in openapi["paths"]:
        lines.extend(
            [
                "export async function exchangeBrowserSession(",
                "  baseUrl: string, bootstrapNonce: string, signal?: AbortSignal,",
                "): Promise<SessionExchangeReceiptResponse> {",
                "  const response = await globalThis.fetch(`${baseUrl}/api/v1/session/exchange`, {",
                "    method: 'POST',",
                "    headers: { 'content-type': 'application/json' },",
                "    body: JSON.stringify({ bootstrap_nonce: bootstrapNonce }),",
                "    ...(signal === undefined ? {} : { signal }),",
                "  });",
                (
                    "  if (!response.ok) throw new Error("
                    "`Session exchange failed with ${response.status}`);"
                ),
                "  return await response.json() as SessionExchangeReceiptResponse;",
                "}",
                "",
            ]
        )
    if "/api/v1/commands" in openapi["paths"]:
        lines.extend(
            [
                (
                    "export type CommandEnvelope = WorkspaceCreateEnvelope | "
                    "MessageSubmitEnvelope | WaitingAnswerEnvelope | TurnPauseRequestEnvelope | "
                    "ResearchPathBranchEnvelope;"
                ),
                "export type ApiResult<T> =",
                "  | { readonly ok: true; readonly status: number; readonly data: T }",
                (
                    "  | { readonly ok: false; readonly status: number; "
                    "readonly error: ErrorResponse };"
                ),
                "",
                "export async function submitCommand(",
                "  baseUrl: string,",
                "  command: CommandEnvelope,",
                "  signal?: AbortSignal,",
                "): Promise<ApiResult<CommandReceiptResponse>> {",
                "  const response = await apiFetch(`${baseUrl}/api/v1/commands`, {",
                "    method: 'POST',",
                "    headers: { 'content-type': 'application/json' },",
                "    body: JSON.stringify(command),",
                "    ...(signal === undefined ? {} : { signal }),",
                "  });",
                "  const payload: unknown = await response.json();",
                "  if (response.ok) {",
                (
                    "    return { ok: true, status: response.status, "
                    "data: payload as CommandReceiptResponse };"
                ),
                "  }",
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspace-attention" in openapi["paths"]:
        lines.extend(
            [
                "export async function getWorkspaceAttention(",
                "  baseUrl: string, signal?: AbortSignal,",
                "): Promise<ApiResult<GlobalAttentionResponse>> {",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspace-attention`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const payload: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: payload as GlobalAttentionResponse };"
                ),
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspace-attention/events" in openapi["paths"]:
        lines.extend(
            [
                "export function workspaceAttentionEventStreamUrl(baseUrl: string): string {",
                "  return `${baseUrl}/api/v1/workspace-attention/events`;",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/execution" in openapi["paths"]:
        lines.extend(
            [
                "export async function getWorkspaceExecution(",
                "  baseUrl: string,",
                "  workspaceId: string,",
                "  signal?: AbortSignal,",
                "): Promise<ApiResult<WorkspaceExecutionResponse>> {",
                "  const encoded = encodeURIComponent(workspaceId);",
                (
                    "  const response = await apiFetch("
                    "`${baseUrl}/api/v1/workspaces/${encoded}/execution`,"
                ),
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const payload: unknown = await response.json();",
                "  if (response.ok) {",
                (
                    "    return { ok: true, status: response.status, "
                    "data: payload as WorkspaceExecutionResponse };"
                ),
                "  }",
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/bootstrap" in openapi["paths"]:
        lines.extend(
            [
                "export async function getWorkspaceBootstrap(",
                "  baseUrl: string,",
                "  workspaceId: string,",
                "  signal?: AbortSignal,",
                "): Promise<ApiResult<WorkspaceBootstrapResponse>> {",
                "  const encoded = encodeURIComponent(workspaceId);",
                (
                    "  const response = await apiFetch("
                    "`${baseUrl}/api/v1/workspaces/${encoded}/bootstrap`,"
                ),
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const payload: unknown = await response.json();",
                "  if (response.ok) {",
                (
                    "    return { ok: true, status: response.status, "
                    "data: payload as WorkspaceBootstrapResponse };"
                ),
                "  }",
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/data-files" in openapi["paths"]:
        lines.extend(
            [
                "export async function getWorkspaceDataCatalog(",
                "  baseUrl: string,",
                "  workspaceId: string,",
                "  signal?: AbortSignal,",
                "): Promise<ApiResult<WorkspaceDataCatalogResponse>> {",
                "  const encoded = encodeURIComponent(workspaceId);",
                (
                    "  const response = await apiFetch("
                    "`${baseUrl}/api/v1/workspaces/${encoded}/data-files`,"
                ),
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const payload: unknown = await response.json();",
                "  if (response.ok) {",
                (
                    "    return { ok: true, status: response.status, "
                    "data: payload as WorkspaceDataCatalogResponse };"
                ),
                "  }",
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/provider-credentials" in openapi["paths"]:
        lines.extend(
            [
                "export async function createProviderCredential(",
                "  baseUrl: string, payload: ProviderCredentialCreateRequest,",
                "): Promise<ApiResult<ProviderCredentialReceiptResponse>> {",
                "  const response = await apiFetch(`${baseUrl}/api/v1/provider-credentials`, {",
                "    method: 'POST',",
                "    headers: { 'Content-Type': 'application/json' },",
                "    body: JSON.stringify(payload),",
                "  });",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as ProviderCredentialReceiptResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
                "export async function getProviderProfiles(",
                "  baseUrl: string, signal?: AbortSignal,",
                "): Promise<ApiResult<ProviderProfileIndexResponse>> {",
                "  const response = await apiFetch(`${baseUrl}/api/v1/provider-credentials`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as ProviderProfileIndexResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
                "export async function rollbackWorkspaceSkill(",
                "  baseUrl: string, workspaceId: string, skillName: string,",
                "  payload: SkillRollbackRequest,",
                "): Promise<ApiResult<SkillAdoptionMutationResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const skill = encodeURIComponent(skillName);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/skills/${skill}/rollback`,",
                "    { method: 'POST', headers: { 'content-type': 'application/json' },",
                "      body: JSON.stringify(payload) },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as SkillAdoptionMutationResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
                "export async function deactivateWorkspaceSkill(",
                "  baseUrl: string, workspaceId: string, skillName: string,",
                "  payload: SkillDeactivateRequest,",
                "): Promise<ApiResult<SkillAdoptionMutationResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const skill = encodeURIComponent(skillName);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/skills/${skill}/deactivate`,",
                "    { method: 'POST', headers: { 'content-type': 'application/json' },",
                "      body: JSON.stringify(payload) },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as SkillAdoptionMutationResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/model-configuration" in openapi["paths"]:
        lines.extend(
            [
                "export async function getWorkspaceModelConfiguration(",
                "  baseUrl: string, workspaceId: string, signal?: AbortSignal,",
                "): Promise<ApiResult<WorkspaceModelConfigurationResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/model-configuration`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as WorkspaceModelConfigurationResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
                "export async function putWorkspaceModelConfiguration(",
                (
                    "  baseUrl: string, workspaceId: string, "
                    "payload: WorkspaceModelConfigurationRequest,"
                ),
                "): Promise<ApiResult<WorkspaceModelConfigurationResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/model-configuration`,",
                (
                    "    { method: 'PUT', headers: { 'Content-Type': 'application/json' }, "
                    "body: JSON.stringify(payload) },"
                ),
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as WorkspaceModelConfigurationResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/conversations/{conversation_id}" in openapi["paths"]:
        lines.extend(
            [
                "export async function getConversationDetail(",
                "  baseUrl: string, workspaceId: string, conversationId: string,",
                "  signal?: AbortSignal,",
                "): Promise<ApiResult<ConversationDetailResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const conversation = encodeURIComponent(conversationId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/conversations/${conversation}`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const payload: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: payload as ConversationDetailResponse };"
                ),
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/turns/{turn_id}/usage" in openapi["paths"]:
        lines.extend(
            [
                "export async function getTurnUsage(",
                "  baseUrl: string, workspaceId: string, turnId: string,",
                "  signal?: AbortSignal,",
                "): Promise<ApiResult<TurnUsageResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const turn = encodeURIComponent(turnId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/turns/${turn}/usage`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const payload: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: payload as TurnUsageResponse };"
                ),
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/turns/{turn_id}/evaluation" in openapi["paths"]:
        lines.extend(
            [
                "export async function getTurnOperationalEvaluation(",
                "  baseUrl: string, workspaceId: string, turnId: string,",
                "  signal?: AbortSignal,",
                "): Promise<ApiResult<TurnOperationalEvaluationResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const turn = encodeURIComponent(turnId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/turns/${turn}/evaluation`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const payload: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: payload as TurnOperationalEvaluationResponse };"
                ),
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
            ]
        )
    if (
        "/api/v1/workspaces/{workspace_id}/turns/{turn_id}/outcome-feedback"
        in openapi["paths"]
    ):
        lines.extend(
            [
                "export async function recordTurnOutcomeFeedback(",
                "  baseUrl: string, workspaceId: string, turnId: string,",
                "  payload: TurnOutcomeFeedbackRequest, signal?: AbortSignal,",
                "): Promise<ApiResult<TurnOutcomeFeedbackResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const turn = encodeURIComponent(turnId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/turns/${turn}/outcome-feedback`,",
                "    { method: 'POST', headers: { 'content-type': 'application/json' },",
                "      body: JSON.stringify(payload),",
                "      ...(signal === undefined ? {} : { signal }) },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as TurnOutcomeFeedbackResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
            ]
        )
    if (
        "/api/v1/workspaces/{workspace_id}/research-paths/{research_path_id}/plan"
        in openapi["paths"]
    ):
        lines.extend(
            [
                "export async function getResearchPlan(",
                "  baseUrl: string, workspaceId: string, researchPathId: string,",
                "  signal?: AbortSignal,",
                "): Promise<ApiResult<ResearchPlanResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const path = encodeURIComponent(researchPathId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/research-paths/${path}/plan`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const payload: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: payload as ResearchPlanResponse };"
                ),
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
            ]
        )
    if (
        "/api/v1/workspaces/{workspace_id}/research-paths/{research_path_id}/results"
        in openapi["paths"]
    ):
        lines.extend(
            [
                "export async function getResultIndex(",
                "  baseUrl: string, workspaceId: string, researchPathId: string,",
                "  signal?: AbortSignal,",
                "): Promise<ApiResult<ResultIndexResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const path = encodeURIComponent(researchPathId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/research-paths/${path}/results`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const payload: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: payload as ResultIndexResponse };"
                ),
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/analysis-outputs" in openapi["paths"]:
        lines.extend(
            [
                "export async function getAnalysisOutputIndex(",
                "  baseUrl: string, workspaceId: string, signal?: AbortSignal,",
                "): Promise<ApiResult<AnalysisOutputIndexResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/analysis-outputs`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const payload: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: payload as AnalysisOutputIndexResponse };"
                ),
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/artifacts/{artifact_id}/content" in openapi["paths"]:
        lines.extend(
            [
                "export async function getArtifactContent(",
                "  baseUrl: string, workspaceId: string, artifactId: string,",
                "  signal?: AbortSignal,",
                "): Promise<Response> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const artifact = encodeURIComponent(artifactId);",
                "  return await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/artifacts/${artifact}/content`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "}",
                "",
            ]
        )
    if (
        "/api/v1/workspaces/{workspace_id}/research-paths/{research_path_id}/documents"
        in openapi["paths"]
    ):
        lines.extend(
            [
                "export async function getDocumentIndex(",
                "  baseUrl: string, workspaceId: string, researchPathId: string,",
                "  signal?: AbortSignal,",
                "): Promise<ApiResult<DocumentIndexResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const path = encodeURIComponent(researchPathId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/research-paths/${path}/documents`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const payload: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: payload as DocumentIndexResponse };"
                ),
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/journal-entries" in openapi["paths"]:
        lines.extend(
            [
                "export type JournalQuery = {",
                "  readonly cursor?: string;",
                "  readonly pageSize?: number;",
                "  readonly sort?: 'asc' | 'desc';",
                "  readonly turnId?: string;",
                "};",
                "",
                "export async function getJournalEntries(",
                "  baseUrl: string, workspaceId: string, query: JournalQuery = {},",
                "  signal?: AbortSignal,",
                "): Promise<ApiResult<JournalEntryPageResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const search = new URLSearchParams();",
                "  if (query.cursor !== undefined) search.set('cursor', query.cursor);",
                (
                    "  if (query.pageSize !== undefined) search.set('page_size', "
                    "String(query.pageSize));"
                ),
                "  if (query.sort !== undefined) search.set('sort', query.sort);",
                "  if (query.turnId !== undefined) search.set('turn_id', query.turnId);",
                "  const suffix = search.size === 0 ? '' : `?${search.toString()}`;",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/journal-entries${suffix}`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const payload: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: payload as JournalEntryPageResponse };"
                ),
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/stream-head" in openapi["paths"]:
        lines.extend(
            [
                "export async function getWorkspaceStreamHead(",
                "  baseUrl: string, workspaceId: string, after: string,",
                "  signal?: AbortSignal,",
                "): Promise<ApiResult<WorkspaceStreamHeadResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const query = new URLSearchParams({ after });",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/stream-head?${query.toString()}`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const payload: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: payload as WorkspaceStreamHeadResponse };"
                ),
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/events" in openapi["paths"]:
        lines.extend(
            [
                "export function workspaceEventStreamUrl(",
                "  baseUrl: string, workspaceId: string, after: string,",
                "): string {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const query = new URLSearchParams({ after });",
                "  return `${baseUrl}/api/v1/workspaces/${workspace}/events?${query.toString()}`;",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/lineage" in openapi["paths"]:
        lines.extend(
            [
                "export async function getEvidenceLineage(",
                "  baseUrl: string,",
                "  workspaceId: string,",
                "  entryKind: LineageEntryKind,",
                "  entryId: string,",
                "  entrySubkey?: string,",
                "  signal?: AbortSignal,",
                "): Promise<ApiResult<EvidenceLineageResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                (
                    "  const query = new URLSearchParams("
                    "{ entry_kind: entryKind, entry_id: entryId });"
                ),
                "  if (entrySubkey !== undefined) query.set('entry_subkey', entrySubkey);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/lineage?${query.toString()}` ,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const payload: unknown = await response.json();",
                "  if (response.ok) {",
                (
                    "    return { ok: true, status: response.status, "
                    "data: payload as EvidenceLineageResponse };"
                ),
                "  }",
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/memories" in openapi["paths"]:
        lines.extend(
            [
                "export async function getMemoryIndex(",
                "  baseUrl: string, workspaceId: string, signal?: AbortSignal,",
                "): Promise<ApiResult<MemoryIndexResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/memories`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const payload: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: payload as MemoryIndexResponse };"
                ),
                "  return { ok: false, status: response.status, error: payload as ErrorResponse };",
                "}",
                "",
                "export async function activateMemory(",
                "  baseUrl: string, workspaceId: string, memoryItemId: string,",
                "  payload: MemoryActivationRequest,",
                "): Promise<ApiResult<MemoryMutationResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const item = encodeURIComponent(memoryItemId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/memories/${item}/activate`,",
                "    { method: 'POST', headers: { 'content-type': 'application/json' },",
                "      body: JSON.stringify(payload) },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as MemoryMutationResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
                "export async function reviseMemory(",
                "  baseUrl: string, workspaceId: string, memoryItemId: string,",
                "  payload: MemoryRevisionRequest,",
                "): Promise<ApiResult<MemoryMutationResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const item = encodeURIComponent(memoryItemId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/memories/${item}/revise`,",
                "    { method: 'POST', headers: { 'content-type': 'application/json' },",
                "      body: JSON.stringify(payload) },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as MemoryMutationResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
                "export async function retractMemory(",
                "  baseUrl: string, workspaceId: string, memoryItemId: string,",
                "  payload: MemoryRetractionRequest,",
                "): Promise<ApiResult<MemoryMutationResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const item = encodeURIComponent(memoryItemId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/memories/${item}/retract`,",
                "    { method: 'POST', headers: { 'content-type': 'application/json' },",
                "      body: JSON.stringify(payload) },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as MemoryMutationResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/skill-evolution-candidates" in openapi["paths"]:
        lines.extend(
            [
                "export async function getSkillEvolutionCandidates(",
                "  baseUrl: string, workspaceId: string, signal?: AbortSignal,",
                "): Promise<ApiResult<SkillEvolutionIndexResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/skill-evolution-candidates`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as SkillEvolutionIndexResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
                "export async function evaluateWorkspaceSkill(",
                "  baseUrl: string, workspaceId: string, skillName: string,",
                "  payload: SkillEvaluationRequest,",
                "): Promise<ApiResult<SkillEvaluationResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const skill = encodeURIComponent(skillName);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/skills/${skill}/evaluations`,",
                "    { method: 'POST', headers: { 'content-type': 'application/json' },",
                "      body: JSON.stringify(payload) },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as SkillEvaluationResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
                "export async function materializeSkillChange(",
                "  baseUrl: string, workspaceId: string, proposalId: string,",
                "  payload: SkillChangeMaterializeRequest,",
                "): Promise<ApiResult<SkillChangeMutationResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const proposal = encodeURIComponent(proposalId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/skill-improvement-proposals/` +",
                "      `${proposal}/materialize`,",
                "    { method: 'POST', headers: { 'content-type': 'application/json' },",
                "      body: JSON.stringify(payload) },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as SkillChangeMutationResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
                "export async function activateSkillChange(",
                "  baseUrl: string, workspaceId: string, candidateId: string,",
                "  payload: SkillChangeActivateRequest,",
                "): Promise<ApiResult<SkillChangeMutationResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const candidate = encodeURIComponent(candidateId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/skill-change-candidates/` +",
                "      `${candidate}/activate`,",
                "    { method: 'POST', headers: { 'content-type': 'application/json' },",
                "      body: JSON.stringify(payload) },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as SkillChangeMutationResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
                "export async function rejectSkillChange(",
                "  baseUrl: string, workspaceId: string, candidateId: string,",
                "  payload: SkillChangeRejectRequest,",
                "): Promise<ApiResult<SkillChangeMutationResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const candidate = encodeURIComponent(candidateId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/skill-change-candidates/` +",
                "      `${candidate}/reject`,",
                "    { method: 'POST', headers: { 'content-type': 'application/json' },",
                "      body: JSON.stringify(payload) },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as SkillChangeMutationResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
                "export async function activateSkillEvolutionCandidate(",
                "  baseUrl: string, workspaceId: string, candidateId: string,",
                "  payload: SkillEvolutionApproveRequest,",
                "): Promise<ApiResult<SkillEvolutionMutationResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const candidate = encodeURIComponent(candidateId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/skill-evolution-candidates/` +",
                "      `${candidate}/activate`,",
                "    { method: 'POST', headers: { 'content-type': 'application/json' },",
                "      body: JSON.stringify(payload) },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as SkillEvolutionMutationResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
                "export async function rejectSkillEvolutionCandidate(",
                "  baseUrl: string, workspaceId: string, candidateId: string,",
                "  payload: SkillEvolutionRejectRequest,",
                "): Promise<ApiResult<SkillEvolutionMutationResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const candidate = encodeURIComponent(candidateId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/skill-evolution-candidates/` +",
                "      `${candidate}/reject`,",
                "    { method: 'POST', headers: { 'content-type': 'application/json' },",
                "      body: JSON.stringify(payload) },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as SkillEvolutionMutationResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
            ]
        )
    if "/api/v1/workspaces/{workspace_id}/knowledge-index" in openapi["paths"]:
        lines.extend(
            [
                "export async function getKnowledgeIndex(",
                "  baseUrl: string, workspaceId: string, signal?: AbortSignal,",
                "): Promise<ApiResult<KnowledgeIndexResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/knowledge-index`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as KnowledgeIndexResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
            ]
        )
    policy_path = "/api/v1/workspaces/{workspace_id}/conversations/{conversation_id}/memory-policy"
    if policy_path in openapi["paths"]:
        lines.extend(
            [
                "export async function getConversationMemoryPolicy(",
                "  baseUrl: string, workspaceId: string, conversationId: string,",
                "  signal?: AbortSignal,",
                "): Promise<ApiResult<ConversationMemoryPolicyResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const conversation = encodeURIComponent(conversationId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/conversations/` +",
                "      `${conversation}/memory-policy`,",
                "    signal === undefined ? {} : { signal },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as ConversationMemoryPolicyResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
                "export async function putConversationMemoryPolicy(",
                "  baseUrl: string, workspaceId: string, conversationId: string,",
                "  payload: ConversationMemoryPolicyRequest,",
                "): Promise<ApiResult<ConversationMemoryPolicyResponse>> {",
                "  const workspace = encodeURIComponent(workspaceId);",
                "  const conversation = encodeURIComponent(conversationId);",
                "  const response = await apiFetch(",
                "    `${baseUrl}/api/v1/workspaces/${workspace}/conversations/` +",
                "      `${conversation}/memory-policy`,",
                "    { method: 'PUT', headers: { 'content-type': 'application/json' },",
                "      body: JSON.stringify(payload) },",
                "  );",
                "  const body: unknown = await response.json();",
                (
                    "  if (response.ok) return { ok: true, status: response.status, "
                    "data: body as ConversationMemoryPolicyResponse };"
                ),
                "  return { ok: false, status: response.status, error: body as ErrorResponse };",
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def build_ipc_schema() -> dict[str, Any]:
    return {
        "schema_version": "1",
        "main_to_worker": TypeAdapter(WorkerIpcInput).json_schema(),
        "worker_to_main": TypeAdapter(AgentIpcMessage).json_schema(),
    }


def build_tool_schema() -> dict[str, Any]:
    return {
        "schema_version": "1",
        "schemas": {
            model.__name__: model.model_json_schema()
            for model in (
                CanonicalToolCallEnvelope,
                OperationEnvelope,
                OperationAttemptEnvelope,
                CompletionManifestEnvelope,
                CanonicalToolResultEnvelope,
            )
        },
    }


def main() -> None:
    with tempfile.TemporaryDirectory(prefix="stata-agent-contract-") as temporary:
        app = create_app(WorkspaceHost(Path(temporary)))
        openapi = app.openapi()
    write_json(ROOT / "contracts" / "api" / "openapi-v1.json", openapi)
    write_json(
        ROOT / "contracts" / "ipc" / "agent-ipc-v2.schema.json",
        build_ipc_schema(),
    )
    write_json(
        ROOT / "contracts" / "tools" / "tool-contract-v1.schema.json",
        build_tool_schema(),
    )
    generated = ROOT / "web" / "src" / "generated" / "api-v1.ts"
    generated.parent.mkdir(parents=True, exist_ok=True)
    generated.write_text(generate_typescript(openapi), encoding="utf-8")


if __name__ == "__main__":
    main()
